site_name: Руководство пользователя XPlan # Название сайта
site_description: Тестовый сайт для отработки гипотезы. # Описание сайта

theme: # Конфигурация используемой темы
  name: material
  language: ru # Системный язык (кнопка "К началу", плейсхолдер "Поиск" и т.д.)
  features:
    - navigation.tabs # Навигация в виде табов
    - navigation.sections # Секции в навигации
    - navigation.top # Кнопка "К началу"
    # - search.suggest # Подсказки при поиске
    # - content.code.copy # Кнопка "копировать" для блоков кода
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette: # Визуальное оформление
    - scheme: default # Светлая тема
      primary: 'indigo' # light blue
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Переключиться на тёмную тему
    - scheme: slate # Тёмная тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлую тему

nav: # Структура сайта
  - Разделы XPlan:
    - Раздел "Персональные данные": Sections/Personal-data/Personal-data-adm.md
    - Раздел "Рабочие группы": Sections/Working-groups/Working-groups-adm.md
  - Инструкции: test-file-1.md
  - Глоссарий: test-file-2.md
  - Что нового: test-file-3.md

markdown_extensions:
  - admonition  # базовые выноски
  - pymdownx.details  # расширенные выноски
  - pymdownx.superfences

markdown_extensions: # Подсветка синтаксиса в блоках кода
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions: # Выравнивание изображений
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

markdown_extensions: # Заголовок блока "Содержание" на русском
  - toc:
      title: Содержание

plugins:
  - search
  - external-markdown
  - include-markdown
  
extra_css: # Переносы в выносках
  - stylesheets/extra.css