site_name: Руководство пользователя XPlan
site_description: Тестовый сайт для отработки гипотезы.

theme:
  name: material
  features:
    - navigation.tabs # Навигация в виде табов
    - navigation.sections # Секции в навигации
    - toc.integrate # Интегрировать оглавление страницы в навигацию
    - search.suggest # Подсказки при поиске
    - content.code.copy # Кнопка "копировать" для блоков кода

  palette:
    - scheme: default # Светлая тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Переключиться на тёмную тему
    - scheme: slate # Темная тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлую тему

nav:
    - Разделы XPlan:
      - Персональные данные: Sections\Personal-data\Personal-data-adm.md
      - Рабочие группы: Sections\Working-groups\Working-groups-adm.md
    - Инструкции: test-file-1.md
    - Глоссарий: test-file-2.md
    - Что нового: test-file-3.md

markdown_extensions:
  - admonition # Блоки !!! note, !!! warning
  - pymdownx.details # Сворачиваемые блоки
  - pymdownx.superfences # Вложенные блоки кода
  - pymdownx.tabbed: # Табы
      alternate_style: true

markdown_extensions: # Заголовок блока "Содержание"
  - toc:
      title: Содержание