site_name: MkDocsWorkTest
site_url:
site_description: Тестовый репозиторий для отработки гипотезы.
site_author: Frolov Aleksey
repo_url: https://github.com/daymonri/MkDocsWorkTest.git
theme: material
copyright: Copyright &copy; 2025

nav:
    - Разделы:
        - Рабочие группы: Rabocie-gruppi-root.md
    - Инструкции: test-file.md
    - Глоссарий: test-file.md
    - Release Notes: test-file.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

markdown_extensions:
  - toc:
      title: Содержание