site_name: Руководство пользователя
site_url: https://daymonri.github.io/MkDocsWorkTest/
site_description: Тестовый репозиторий для отработки гипотезы.
site_author: Aleksey Frolov
repo_url: https://github.com/daymonri/MkDocsWorkTest.git

theme: material

nav:
    - Разделы системы:
        - Рабочие группы: Sections\Working-groups\Working-groups-root.md
    - Инструкции: test-file-1.md
    - Глоссарий: test-file-2.md
    - Что нового: test-file-3.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

markdown_extensions:
  - toc:
      title: Содержание

copyright: Copyright &copy; 2025