site_name: Руководство пользователя XPlan
site_description: Тестовый сайт для отработки гипотезы.

theme:
  name: material
  features:
    - navigation.tabs # Навигация в виде табов
    - navigation.sections # Секции в навигации
    - toc.integrate # Интегрировать оглавление страницы в навигацию
    - search.suggest # Подсказки при поиске
    - content.code.copy # Кнопка "копировать" для блоков кода
    - navigation.indexes # Убрать дублирование названий разделов в левом меню
    - navigation.top # Кнопка "Вернуться к началу"

  palette:
    - scheme: default # Светлая тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Переключиться на тёмную тему
    - scheme: slate # Тёмная тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлую тему

nav:
  - Разделы XPlan:
    - test-file-4-1.md
    - test-file-4-2.md
  - Инструкции: test-file-1.md
  - Глоссарий: test-file-2.md
  - Что нового: test-file-3.md

markdown_extensions:
  - admonition # Блоки !!! note, !!! warning
  - pymdownx.details # Сворачиваемые блоки
  - pymdownx.superfences # Вложенные блоки кода
  - pymdownx.tabbed: # Табы
      alternate_style: true

markdown_extensions: # Подсветка синтаксиса
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions: # Для выравнивания изображений
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

markdown_extensions: # Заголовок блока "Содержание"
  - toc:
      title: Содержание

plugins: # Локализация системных слов (поиск, предыдудщий, следующий)
  - i18n:
      docs_structure: suffix
      default_language: ru
      languages:
        ru:
          name: Russian
          build: true
          site_name: "Руководство пользователя XPlan"